packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-python: set this to true or false
  tree-sitter-typescript: set this to true or false
  unrs-resolver: set this to true or false
