/**
 * File filtering: binary detection, generated file heuristics, size limits.
 * Integrates with IgnoreMatcher for comprehensive file filtering.
 */

import { lstat, readFile, stat } from 'node:fs/promises';
import { basename, extname, relative, resolve } from 'node:path';
import { createLogger } from '../logging/index.js';
import type { IgnoreMatcher } from './ignore.js';

const logger = createLogger('file-filter');

/**
 * Configuration options for FileFilter.
 */
export interface FileFilterOptions {
  /** Maximum file size in bytes (default: 10MB) */
  maxFileSize?: number;
  /** Whether to detect binary files (default: true) */
  detectBinary?: boolean;
  /** Whether to detect generated files (default: true) */
  detectGenerated?: boolean;
  /** Whether to follow symlinks (default: false) */
  followSymlinks?: boolean;
  /** Repository root for symlink validation */
  repoRoot?: string;
}

/**
 * Result of file analysis.
 */
export interface FileAnalysisResult {
  /** Whether the file should be analyzed */
  shouldAnalyze: boolean;
  /** Reason if not analyzed */
  reason?: string;
  /** File size in bytes */
  size: number;
  /** Whether file is binary */
  isBinary: boolean;
  /** Whether file is generated */
  isGenerated: boolean;
  /** File extension */
  extension: string;
}

/**
 * Default configuration.
 */
const DEFAULT_OPTIONS: Required<FileFilterOptions> = {
  maxFileSize: 10 * 1024 * 1024, // 10MB
  detectBinary: true,
  detectGenerated: true,
  followSymlinks: false,
  repoRoot: process.cwd(),
};

/**
 * Generated file detection patterns.
 * These are common markers indicating a file was generated by a tool.
 */
const GENERATED_FILE_MARKERS = [
  // TypeScript/JavaScript generated files
  '// @generated',
  '// Generated by',
  '/* Generated by',
  '// This file is generated',
  '// This file was generated',
  '// DO NOT EDIT',
  '// DO NOT MODIFY',
  '/* eslint-disable */',
  '// biome-ignore',
  // Source map files
  '//# sourceMappingURL=',
  // Minified file indicators (first line very long with few newlines)
  // CSS/JS minified
  '/*! ',
  // Python generated
  '# Generated by',
  '# This file is generated',
  // Go generated
  '// Code generated by',
  '// DO NOT EDIT',
  // Rust generated
  '// Generated by',
  // Java generated
  '// Generated by',
  // Protobuf
  '// Generated by the protocol buffer compiler',
  // GraphQL
  '// Generated by graphql-codegen',
];

/**
 * Binary file extensions that are always treated as binary.
 */
const BINARY_EXTENSIONS = new Set([
  // Images
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.bmp',
  '.ico',
  '.tiff',
  '.webp',
  '.avif',
  // Audio
  '.mp3',
  '.wav',
  '.ogg',
  '.flac',
  '.aac',
  '.m4a',
  // Video
  '.mp4',
  '.webm',
  '.mov',
  '.avi',
  '.mkv',
  // Archives
  '.zip',
  '.tar',
  '.gz',
  '.rar',
  '.7z',
  '.bz2',
  '.xz',
  // Executables
  '.exe',
  '.dll',
  '.so',
  '.dylib',
  '.bin',
  // Documents
  '.pdf',
  '.doc',
  '.docx',
  '.xls',
  '.xlsx',
  '.ppt',
  '.pptx',
  // Fonts
  '.woff',
  '.woff2',
  '.ttf',
  '.otf',
  '.eot',
  // Database
  '.sqlite',
  '.db',
  '.mdb',
  // Compiled
  '.class',
  '.pyc',
  '.pyo',
  '.o',
  '.obj',
  // Other
  '.swf',
  '.fla',
  '.psd',
  '.ai',
  '.sketch',
]);

/**
 * Text file extensions that are always treated as text (even if they match binary patterns).
 */
const TEXT_EXTENSIONS = new Set([
  '.txt',
  '.md',
  '.json',
  '.yaml',
  '.yml',
  '.toml',
  '.ini',
  '.cfg',
  '.conf',
  '.js',
  '.ts',
  '.jsx',
  '.tsx',
  '.mjs',
  '.cjs',
  '.py',
  '.rb',
  '.php',
  '.java',
  '.kt',
  '.scala',
  '.go',
  '.rs',
  '.swift',
  '.c',
  '.cpp',
  '.h',
  '.hpp',
  '.cc',
  '.cxx',
  '.cs',
  '.vb',
  '.fs',
  '.fsx',
  '.html',
  '.htm',
  '.xml',
  '.svg',
  '.css',
  '.scss',
  '.sass',
  '.less',
  '.sh',
  '.bash',
  '.zsh',
  '.fish',
  '.ps1',
  '.sql',
  '.graphql',
  '.gql',
  '.proto',
  '.thrift',
  '.dockerfile',
  '.dockerignore',
  '.gitignore',
  '.gitattributes',
  '.gitmodules',
  '.editorconfig',
  '.eslintrc',
  '.prettierrc',
  '.biome.json',
  '.env',
  '.env.example',
  '.env.local',
]);

/**
 * Checks if a file extension is a known binary type.
 */
function isKnownBinaryExtension(filePath: string): boolean {
  const ext = extname(filePath).toLowerCase();
  return BINARY_EXTENSIONS.has(ext);
}

/**
 * Checks if a file extension is a known text type.
 */
function isKnownTextExtension(filePath: string): boolean {
  const ext = extname(filePath).toLowerCase();
  return TEXT_EXTENSIONS.has(ext);
}

/**
 * Checks if a file is binary by reading a sample and checking for null bytes
 * or valid UTF-8 encoding.
 */
export async function isBinaryFile(filePath: string, sampleSize: number = 8192): Promise<boolean> {
  // Quick check by extension first
  if (isKnownBinaryExtension(filePath)) {
    return true;
  }
  if (isKnownTextExtension(filePath)) {
    return false;
  }

  try {
    const stats = await stat(filePath);
    // Empty files are not binary
    if (stats.size === 0) {
      return false;
    }

    // Read a sample of the file
    const buffer = Buffer.alloc(Math.min(sampleSize, stats.size));
    const fileHandle = await readFile(filePath);
    const sample = fileHandle.subarray(0, buffer.length);

    // Check for null bytes (strong indicator of binary)
    if (sample.includes(0)) {
      return true;
    }

    // Check if it's valid UTF-8
    try {
      sample.toString('utf-8');
      return false;
    } catch {
      return true;
    }
  } catch (error) {
    logger.warn({ filePath, error }, 'Failed to check if file is binary, assuming text');
    return false;
  }
}

/**
 * Checks if a file appears to be generated by a tool.
 * Reads the first few lines and looks for common generated file markers.
 */
export async function isGeneratedFile(filePath: string, maxLines: number = 20): Promise<boolean> {
  try {
    const content = await readFile(filePath, 'utf-8');
    const lines = content.split('\n').slice(0, maxLines);

    for (const line of lines) {
      const trimmed = line.trim();
      for (const marker of GENERATED_FILE_MARKERS) {
        if (trimmed.includes(marker)) {
          return true;
        }
      }
    }

    // Check for minified files: first line very long with few newlines
    const firstLine = lines[0] || '';
    if (firstLine.length > 500 && lines.length < 5) {
      // Likely minified
      return true;
    }

    // Check for source map files
    if (basename(filePath).endsWith('.map')) {
      return true;
    }

    return false;
  } catch (_error) {
    // If we can't read it as text, it might be binary
    return false;
  }
}

/**
 * Checks if a symlink target is within the repository root.
 * Prevents symlink traversal attacks.
 */
export async function isSymlinkSafe(linkPath: string, repoRoot: string): Promise<boolean> {
  try {
    const { realpath } = await import('node:fs/promises');
    const resolved = await realpath(linkPath);
    const resolvedRepoRoot = await realpath(repoRoot);
    return resolved.startsWith(`${resolvedRepoRoot}/`) || resolved === resolvedRepoRoot;
  } catch {
    return false;
  }
}

/**
 * Main file filter class that combines ignore patterns, binary detection,
 * generated file detection, and size limits.
 */
export class FileFilter {
  private options: Required<FileFilterOptions>;
  private ignoreMatcher: IgnoreMatcher | null = null;

  constructor(options: FileFilterOptions = {}) {
    this.options = { ...DEFAULT_OPTIONS, ...options };
  }

  /**
   * Sets the ignore matcher to use for filtering.
   */
  setIgnoreMatcher(matcher: IgnoreMatcher): void {
    this.ignoreMatcher = matcher;
  }

  /**
   * Checks if a file should be analyzed based on all filters.
   */
  async shouldAnalyzeFile(filePath: string): Promise<FileAnalysisResult> {
    const absolutePath = resolve(this.options.repoRoot, filePath);
    const relativePath = relative(this.options.repoRoot, absolutePath).split('\\').join('/');

    // 1. Check ignore patterns
    if (this.ignoreMatcher?.ignores(relativePath)) {
      return {
        shouldAnalyze: false,
        reason: 'ignored by pattern',
        size: 0,
        isBinary: false,
        isGenerated: false,
        extension: extname(filePath),
      };
    }

    // 2. Check file exists and get stats
    let stats: Awaited<ReturnType<typeof stat>>;
    let lstats: Awaited<ReturnType<typeof lstat>>;
    try {
      stats = await stat(absolutePath);
      lstats = await lstat(absolutePath);
    } catch (_error) {
      return {
        shouldAnalyze: false,
        reason: 'file not accessible',
        size: 0,
        isBinary: false,
        isGenerated: false,
        extension: extname(filePath),
      };
    }

    const size = stats.size;

    // 3. Check size limit
    if (size > this.options.maxFileSize) {
      logger.debug(
        { filePath: relativePath, size, limit: this.options.maxFileSize },
        'File exceeds size limit'
      );
      return {
        shouldAnalyze: false,
        reason: `file size ${size} exceeds limit ${this.options.maxFileSize}`,
        size,
        isBinary: false,
        isGenerated: false,
        extension: extname(filePath),
      };
    }

    // 4. Check symlink safety
    if (!this.options.followSymlinks && lstats.isSymbolicLink()) {
      const isSafe = await isSymlinkSafe(absolutePath, this.options.repoRoot);
      if (!isSafe) {
        return {
          shouldAnalyze: false,
          reason: 'symlink target outside repository',
          size,
          isBinary: false,
          isGenerated: false,
          extension: extname(filePath),
        };
      }
    }

    // 5. Check binary detection
    let isBinary = false;
    if (this.options.detectBinary) {
      isBinary = await isBinaryFile(absolutePath);
      if (isBinary) {
        return {
          shouldAnalyze: false,
          reason: 'binary file',
          size,
          isBinary: true,
          isGenerated: false,
          extension: extname(filePath),
        };
      }
    }

    // 6. Check generated file detection
    let isGenerated = false;
    if (this.options.detectGenerated && !isBinary) {
      isGenerated = await isGeneratedFile(absolutePath);
      if (isGenerated) {
        return {
          shouldAnalyze: false,
          reason: 'generated file',
          size,
          isBinary: false,
          isGenerated: true,
          extension: extname(filePath),
        };
      }
    }

    return {
      shouldAnalyze: true,
      size,
      isBinary,
      isGenerated,
      extension: extname(filePath),
    };
  }

  /**
   * Filters an array of file paths, returning only those that should be analyzed.
   */
  async filterFiles(filePaths: string[]): Promise<string[]> {
    const results = await Promise.all(
      filePaths.map(async (filePath) => {
        const result = await this.shouldAnalyzeFile(filePath);
        return { filePath, result };
      })
    );

    const analyzed = results
      .filter(({ result }) => result.shouldAnalyze)
      .map(({ filePath }) => filePath);

    const ignored = results
      .filter(({ result }) => !result.shouldAnalyze)
      .map(({ filePath, result }) => ({ filePath, reason: result.reason }));

    if (ignored.length > 0) {
      logger.debug(
        { ignored: ignored.length, reasons: ignored.map((i) => i.reason) },
        'Files filtered out'
      );
    }

    return analyzed;
  }
}

/**
 * Creates a FileFilter with default options.
 */
export function createFileFilter(options: FileFilterOptions = {}): FileFilter {
  return new FileFilter(options);
}

/**
 * Convenience function to check if a file should be analyzed.
 * Creates a temporary FileFilter with the given ignore matcher.
 */
export async function shouldAnalyzeFile(
  filePath: string,
  ignoreMatcher: IgnoreMatcher,
  options: FileFilterOptions = {}
): Promise<FileAnalysisResult> {
  const filter = createFileFilter(options);
  filter.setIgnoreMatcher(ignoreMatcher);
  return await filter.shouldAnalyzeFile(filePath);
}
