/**
 * Tests for file filtering: binary detection, generated file heuristics, size limits.
 */

import { randomUUID } from 'node:crypto';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import {
  createFileFilter,
  FileFilter,
  isBinaryFile,
  isBinaryFileFast,
  isGeneratedFile,
  isSymlink,
  resolveSymlinkSafely,
} from './filter.js';
import { createIgnoreMatcher } from './ignore.js';

const TEST_DIR = join(tmpdir(), `octate-filter-test-${randomUUID()}`);

async function setupTestFile(relativePath: string, content: string | Buffer): Promise<string> {
  const fullPath = resolve(TEST_DIR, relativePath);
  await mkdir(resolve(fullPath, '..'), { recursive: true });
  await writeFile(fullPath, content);
  return fullPath;
}

beforeAll(async () => {
  await mkdir(TEST_DIR, { recursive: true });
});

afterAll(async () => {
  await rm(TEST_DIR, { recursive: true, force: true });
});

describe('isBinaryFile', () => {
  it('detects text files as non-binary', async () => {
    const filePath = await setupTestFile('text.txt', 'Hello world\nThis is text content');
    const result = await isBinaryFile(filePath);
    expect(result).toBe(false);
  });

  it('detects binary files', async () => {
    const binaryContent = Buffer.from([
      0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x00, 0x77, 0x6f, 0x72, 0x6c, 0x64,
    ]);
    const filePath = await setupTestFile('binary.bin', binaryContent);
    const result = await isBinaryFile(filePath);
    expect(result).toBe(true);
  });
});

describe('isBinaryFileFast', () => {
  it('detects text files as non-binary', async () => {
    const filePath = await setupTestFile(
      'text2.txt',
      'This is plain text content\nWith multiple lines'
    );
    const result = await isBinaryFileFast(filePath);
    expect(result).toBe(false);
  });

  it('detects files with null bytes as binary', async () => {
    const binaryContent = Buffer.from([
      0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x00, 0x77, 0x6f, 0x72, 0x6c, 0x64,
    ]);
    const filePath = await setupTestFile('binary2.bin', binaryContent);
    const result = await isBinaryFileFast(filePath);
    expect(result).toBe(true);
  });

  it('detects high non-printable ratio as binary', async () => {
    const buffer = Buffer.alloc(1000);
    for (let i = 0; i < 1000; i++) {
      buffer[i] = i % 256;
    }
    const filePath = await setupTestFile('high-nonprint.bin', buffer);
    const result = await isBinaryFileFast(filePath);
    expect(result).toBe(true);
  });

  it('detects UTF-8 text with unicode as non-binary', async () => {
    const filePath = await setupTestFile('unicode.txt', 'Hello 世界 🌍\nUnicode content');
    const result = await isBinaryFileFast(filePath);
    expect(result).toBe(false);
  });
});

describe('isGeneratedFile', () => {
  it('detects files with @generated header', async () => {
    const content = '// @generated by some-tool\n// DO NOT EDIT\nexport const x = 1;';
    const filePath = await setupTestFile('generated.ts', content);
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(true);
  });

  it('detects "Generated by" header', async () => {
    const content = '/* Generated by protobuf compiler */\nexport const y = 2;';
    const filePath = await setupTestFile('generated2.ts', content);
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(true);
  });

  it('detects "DO NOT EDIT" header', async () => {
    const content = '// DO NOT EDIT - auto-generated\nconst z = 3;';
    const filePath = await setupTestFile('generated3.js', content);
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(true);
  });

  it('detects eslint-disable as generated', async () => {
    const content = '/* eslint-disable */\nexport const a = 1;';
    const filePath = await setupTestFile('generated4.js', content);
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(true);
  });

  it('detects minified files by extension', async () => {
    const filePath = await setupTestFile('app.min.js', 'const a=1,b=2;');
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(true);
  });

  it('detects source maps as generated', async () => {
    const filePath = await setupTestFile('app.js.map', '{"version":3,"sources":[]}');
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(true);
  });

  it('detects .d.ts as generated', async () => {
    const filePath = await setupTestFile('types.d.ts', 'export declare const x: number;');
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(true);
  });

  it('returns false for regular source files', async () => {
    const content = 'export function hello() {\n  return "world";\n}';
    const filePath = await setupTestFile('regular.ts', content);
    const result = await isGeneratedFile(filePath);
    expect(result).toBe(false);
  });

  it('allows generated when config.allowGenerated is true', async () => {
    const content = '// @generated by tool\nconst x = 1;';
    const filePath = await setupTestFile('generated5.ts', content);
    const result = await isGeneratedFile(filePath, { allowGenerated: true });
    expect(result).toBe(false);
  });
});

describe('FileFilter', () => {
  let ignoreMatcher: ReturnType<typeof createIgnoreMatcher>;

  beforeEach(() => {
    ignoreMatcher = createIgnoreMatcher(['node_modules/**', 'dist/**', '*.log']);
  });

  it('ignores files matching ignore patterns', async () => {
    const filter = new FileFilter(ignoreMatcher);
    const filePath = await setupTestFile('node_modules/foo.js', 'export const x = 1;');
    const result = await filter.analyzeFile(TEST_DIR, filePath);
    expect(result.isIgnored).toBe(true);
    expect(result.shouldAnalyze).toBe(false);
    expect(result.reason).toContain('ignore');
  });

  it('analyzes non-ignored text files', async () => {
    const filter = new FileFilter(ignoreMatcher);
    const filePath = await setupTestFile('src/main.ts', 'export const x = 1;');
    const result = await filter.analyzeFile(TEST_DIR, filePath);
    expect(result.isIgnored).toBe(false);
    expect(result.shouldAnalyze).toBe(true);
  });

  it('excludes binary files', async () => {
    const filter = new FileFilter(ignoreMatcher);
    const binaryContent = Buffer.from([
      0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x00, 0x77, 0x6f, 0x72, 0x6c, 0x64,
    ]);
    const filePath = await setupTestFile('binary.dat', binaryContent);
    const result = await filter.analyzeFile(TEST_DIR, filePath);
    expect(result.isBinary).toBe(true);
    expect(result.shouldAnalyze).toBe(false);
    expect(result.reason).toContain('Binary');
  });

  it('allows binary when config.allowBinary is true', async () => {
    const filter = new FileFilter(ignoreMatcher, { allowBinary: true });
    const binaryContent = Buffer.from([
      0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x00, 0x77, 0x6f, 0x72, 0x6c, 0x64,
    ]);
    const filePath = await setupTestFile('binary2.dat', binaryContent);
    const result = await filter.analyzeFile(TEST_DIR, filePath);
    expect(result.isBinary).toBe(true);
    expect(result.shouldAnalyze).toBe(true);
  });

  it('excludes large files', async () => {
    const filter = new FileFilter(ignoreMatcher, { maxFileSize: 100 });
    const largeContent = 'x'.repeat(200);
    const filePath = await setupTestFile('large.txt', largeContent);
    const result = await filter.analyzeFile(TEST_DIR, filePath);
    expect(result.isLarge).toBe(true);
    expect(result.shouldAnalyze).toBe(false);
    expect(result.reason).toContain('max size');
  });

  it('excludes generated files', async () => {
    const filter = new FileFilter(ignoreMatcher);
    const content = '// @generated by tool\nconst x = 1;';
    const filePath = await setupTestFile('generated.ts', content);
    const result = await filter.analyzeFile(TEST_DIR, filePath);
    expect(result.isGenerated).toBe(true);
    expect(result.shouldAnalyze).toBe(false);
    expect(result.reason).toContain('Generated');
  });

  it('allows generated when config.allowGenerated is true', async () => {
    const filter = new FileFilter(ignoreMatcher, { allowGenerated: true });
    const content = '// @generated by tool\nconst x = 1;';
    const filePath = await setupTestFile('generated2.ts', content);
    const result = await filter.analyzeFile(TEST_DIR, filePath);
    // When allowGenerated is true, we skip the generated check so isGenerated is false
    // but shouldAnalyze is true
    expect(result.isGenerated).toBe(false);
    expect(result.shouldAnalyze).toBe(true);
  });

  it('createFilter returns function for array.filter', () => {
    const filter = new FileFilter(ignoreMatcher);
    const filterFn = filter.createFilter();
    expect(filterFn('src/main.ts')).toBe(true);
    expect(filterFn('node_modules/foo.js')).toBe(false);
    expect(filterFn('dist/bundle.js')).toBe(false);
  });
});

describe('createFileFilter', () => {
  it('creates FileFilter with loaded ignore patterns', async () => {
    await mkdir(resolve(TEST_DIR, 'src'), { recursive: true });
    await writeFile(resolve(TEST_DIR, '.gitignore'), 'node_modules/\ndist/\n*.log\n');
    await writeFile(resolve(TEST_DIR, 'src/index.ts'), 'export const x = 1;');

    const filter = await createFileFilter(TEST_DIR);
    const result = await filter.analyzeFile(TEST_DIR, 'src/index.ts');
    expect(result.shouldAnalyze).toBe(true);
    expect(result.isIgnored).toBe(false);
  });

  it('excludes .gitignore patterns', async () => {
    await writeFile(resolve(TEST_DIR, '.gitignore'), 'ignored/\n');
    await mkdir(resolve(TEST_DIR, 'ignored'), { recursive: true });
    await writeFile(resolve(TEST_DIR, 'ignored/file.txt'), 'ignored');

    const filter = await createFileFilter(TEST_DIR);
    const result = await filter.analyzeFile(TEST_DIR, 'ignored/file.txt');
    expect(result.isIgnored).toBe(true);
  });
});

describe('resolveSymlinkSafely', () => {
  it('resolves relative paths correctly', () => {
    const result = resolveSymlinkSafely(TEST_DIR, 'src/file.txt');
    expect(result.resolvedPath).toContain('src/file.txt');
    expect(result.isSymlink).toBe(false);
  });

  it('throws for paths outside repo root', () => {
    expect(() => resolveSymlinkSafely(TEST_DIR, '../outside.txt')).toThrow(
      'outside repository root'
    );
  });
});

describe('isSymlink', () => {
  it('returns false for regular files', async () => {
    await writeFile(resolve(TEST_DIR, 'regular.txt'), 'content');
    const result = await isSymlink(resolve(TEST_DIR, 'regular.txt'));
    expect(result).toBe(false);
  });

  it('returns false for non-existent files', async () => {
    const result = await isSymlink(resolve(TEST_DIR, 'nonexistent.txt'));
    expect(result).toBe(false);
  });
});
