/**
 * Tests for filter.ts - File filtering: binary detection, generated file heuristics, size limits.
 */

import { randomUUID } from 'node:crypto';
import { mkdir, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from '@jest/globals';
import {
  createFileFilter,
  isBinaryFile,
  isGeneratedFile,
  isSymlinkSafe,
  shouldAnalyzeFile,
} from './filter.js';
import { createIgnoreMatcher } from './ignore.js';

describe('filter', () => {
  let testDir: string;
  let repoRoot: string;

  beforeEach(async () => {
    testDir = join(tmpdir(), `octate-filter-test-${randomUUID()}`);
    repoRoot = join(testDir, 'repo');
    await mkdir(repoRoot, { recursive: true });
  });

  afterEach(async () => {
    await rm(testDir, { recursive: true, force: true });
  });

  describe('isBinaryFile', () => {
    it('detects binary files by extension', async () => {
      await writeFile(join(repoRoot, 'image.png'), 'fake png content');

      const result = await isBinaryFile(join(repoRoot, 'image.png'));

      expect(result).toBe(true);
    });

    it('detects text files by extension', async () => {
      await writeFile(join(repoRoot, 'script.js'), 'console.log("hello");');

      const result = await isBinaryFile(join(repoRoot, 'script.js'));

      expect(result).toBe(false);
    });

    it('detects binary content via null bytes', async () => {
      const binaryContent = Buffer.from([
        0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00,
      ]);
      await writeFile(join(repoRoot, 'unknown.bin'), binaryContent);

      const result = await isBinaryFile(join(repoRoot, 'unknown.bin'));

      expect(result).toBe(true);
    });

    it('detects text content without null bytes', async () => {
      await writeFile(join(repoRoot, 'readme.txt'), 'Hello world\nThis is text');

      const result = await isBinaryFile(join(repoRoot, 'readme.txt'));

      expect(result).toBe(false);
    });

    it('handles empty files as text', async () => {
      await writeFile(join(repoRoot, 'empty.txt'), '');

      const result = await isBinaryFile(join(repoRoot, 'empty.txt'));

      expect(result).toBe(false);
    });

    it('handles missing files gracefully', async () => {
      const result = await isBinaryFile(join(repoRoot, 'nonexistent.txt'));

      expect(result).toBe(false);
    });
  });

  describe('isGeneratedFile', () => {
    it('detects // @generated marker', async () => {
      await writeFile(
        join(repoRoot, 'generated.ts'),
        '// @generated\n// This file was generated\n'
      );

      const result = await isGeneratedFile(join(repoRoot, 'generated.ts'));

      expect(result).toBe(true);
    });

    it('detects // Generated by marker', async () => {
      await writeFile(
        join(repoRoot, 'generated.js'),
        '// Generated by swagger-codegen\n// Do not edit\n'
      );

      const result = await isGeneratedFile(join(repoRoot, 'generated.js'));

      expect(result).toBe(true);
    });

    it('detects /* Generated by */ marker', async () => {
      await writeFile(join(repoRoot, 'generated.css'), '/* Generated by postcss */\nbody {}');

      const result = await isGeneratedFile(join(repoRoot, 'generated.css'));

      expect(result).toBe(true);
    });

    it('detects // DO NOT EDIT marker', async () => {
      await writeFile(
        join(repoRoot, 'generated.ts'),
        '// DO NOT EDIT\n// This file is auto-generated\n'
      );

      const result = await isGeneratedFile(join(repoRoot, 'generated.ts'));

      expect(result).toBe(true);
    });

    it('detects /* eslint-disable */ marker', async () => {
      await writeFile(join(repoRoot, 'generated.js'), '/* eslint-disable */\nconst x = 1;');

      const result = await isGeneratedFile(join(repoRoot, 'generated.js'));

      expect(result).toBe(true);
    });

    it('detects source map files', async () => {
      await writeFile(join(repoRoot, 'bundle.js.map'), '{"version":3,"sources":[]}');

      const result = await isGeneratedFile(join(repoRoot, 'bundle.js.map'));

      expect(result).toBe(true);
    });

    it('detects minified files (long first line)', async () => {
      // Create a very long single line > 500 chars to simulate minified code
      const minified =
        'const a=1,b=2,c=3,d=4,e=5,f=6,g=7,h=8,i=9,j=10,k=11,l=12,m=13,n=14,o=15,p=16,q=17,r=18,s=19,t=20,u=21,v=22,w=23,x=24,y=25,z=26,aa=27,bb=28,cc=29,dd=30,ee=31,ff=32,gg=33,hh=34,ii=35,jj=36,kk=37,ll=38,mm=39,nn=40,oo=41,pp=42,qq=43,rr=44,ss=45,tt=46,uu=47,vv=48,ww=49,xx=50,yy=51,zz=52,aaa=53,bbb=54,ccc=55,ddd=56,eee=57,fff=58,ggg=59,hhh=60,iii=61,jjj=62,kkk=63,lll=64,mmm=65,nnn=66,ooo=67,ppp=68,qqq=69,rrr=70,sss=71,ttt=72,uuu=73,vvv=74,www=75,xxx=76,yyy=77,zzz=78,aaaa=79,bbbb=80,cccc=81,dddd=82,eeee=83,ffff=84,gggg=85,hhhh=86,iiii=87,jjjj=88,kkkk=89,llll=90,mmmm=91,nnnn=92,oooo=93,pppp=94,qqqq=95,rrrr=96,ssss=97,tttt=98,uuuu=99,vvvv=100,wwww=101,xxxx=102,yyyy=103,zzzz=104;';
      await writeFile(join(repoRoot, 'bundle.min.js'), minified);

      const result = await isGeneratedFile(join(repoRoot, 'bundle.min.js'));

      expect(result).toBe(true);
    });

    it('does not flag regular source files', async () => {
      await writeFile(join(repoRoot, 'app.ts'), 'export function hello() {\n  return "world";\n}');

      const result = await isGeneratedFile(join(repoRoot, 'app.ts'));

      expect(result).toBe(false);
    });

    it('detects Python generated marker', async () => {
      await writeFile(join(repoRoot, 'generated.py'), '# Generated by protoc\n# DO NOT EDIT\n');

      const result = await isGeneratedFile(join(repoRoot, 'generated.py'));

      expect(result).toBe(true);
    });

    it('detects Go generated marker', async () => {
      await writeFile(
        join(repoRoot, 'generated.go'),
        '// Code generated by protoc-gen-go. DO NOT EDIT.'
      );

      const result = await isGeneratedFile(join(repoRoot, 'generated.go'));

      expect(result).toBe(true);
    });
  });

  describe('isSymlinkSafe', () => {
    it('allows symlinks within repo', async () => {
      const target = join(repoRoot, 'target.txt');
      await writeFile(target, 'content');
      const link = join(repoRoot, 'link.txt');
      await symlink(target, link);

      const result = await isSymlinkSafe(link, repoRoot);

      expect(result).toBe(true);
    });

    it('rejects symlinks outside repo', async () => {
      const outsideTarget = join(testDir, 'outside.txt');
      await writeFile(outsideTarget, 'content');
      const link = join(repoRoot, 'badlink.txt');
      await symlink(outsideTarget, link);

      const result = await isSymlinkSafe(link, repoRoot);

      expect(result).toBe(false);
    });
  });

  describe('shouldAnalyzeFile', () => {
    it('returns shouldAnalyze true for normal text file', async () => {
      const matcher = createIgnoreMatcher([]);
      await mkdir(join(repoRoot, 'src'), { recursive: true });
      await writeFile(join(repoRoot, 'src', 'app.ts'), 'export const x = 1;');

      const result = await shouldAnalyzeFile('src/app.ts', matcher, { repoRoot });

      expect(result.shouldAnalyze).toBe(true);
      expect(result.isBinary).toBe(false);
      expect(result.isGenerated).toBe(false);
    });

    it('returns shouldAnalyze false for ignored file', async () => {
      const matcher = createIgnoreMatcher(['*.log']);
      await writeFile(join(repoRoot, 'app.log'), 'log content');

      const result = await shouldAnalyzeFile('app.log', matcher, { repoRoot });

      expect(result.shouldAnalyze).toBe(false);
      expect(result.reason).toBe('ignored by pattern');
    });

    it('returns shouldAnalyze false for binary file', async () => {
      const matcher = createIgnoreMatcher([]);
      await writeFile(join(repoRoot, 'image.png'), Buffer.from([0x89, 0x50, 0x4e, 0x47]));

      const result = await shouldAnalyzeFile('image.png', matcher, { repoRoot });

      expect(result.shouldAnalyze).toBe(false);
      expect(result.reason).toBe('binary file');
      expect(result.isBinary).toBe(true);
    });

    it('returns shouldAnalyze false for generated file', async () => {
      const matcher = createIgnoreMatcher([]);
      await writeFile(join(repoRoot, 'generated.ts'), '// @generated\nexport const x = 1;');

      const result = await shouldAnalyzeFile('generated.ts', matcher, { repoRoot });

      expect(result.shouldAnalyze).toBe(false);
      expect(result.reason).toBe('generated file');
      expect(result.isGenerated).toBe(true);
    });

    it('returns shouldAnalyze false for oversized file', async () => {
      const matcher = createIgnoreMatcher([]);
      // Create a file larger than default 10MB limit would be slow, so use small limit
      await writeFile(join(repoRoot, 'large.txt'), 'x'.repeat(100));

      const result = await shouldAnalyzeFile('large.txt', matcher, { repoRoot, maxFileSize: 50 });

      expect(result.shouldAnalyze).toBe(false);
      expect(result.reason).toContain('exceeds limit');
    });

    it('returns shouldAnalyze false for unsafe symlink', async () => {
      const matcher = createIgnoreMatcher([]);
      const outsideTarget = join(testDir, 'outside.txt');
      await writeFile(outsideTarget, 'content');
      const link = join(repoRoot, 'badlink.txt');
      await symlink(outsideTarget, link);

      const result = await shouldAnalyzeFile('badlink.txt', matcher, {
        repoRoot,
        followSymlinks: false,
      });

      expect(result.shouldAnalyze).toBe(false);
      expect(result.reason).toBe('symlink target outside repository');
    });
  });

  describe('FileFilter class', () => {
    it('filters multiple files', async () => {
      const matcher = createIgnoreMatcher(['*.log', 'node_modules/']);

      await mkdir(join(repoRoot, 'src'), { recursive: true });
      await mkdir(join(repoRoot, 'node_modules', 'pkg'), { recursive: true });
      await writeFile(join(repoRoot, 'src', 'app.ts'), 'export const x = 1;');
      await writeFile(join(repoRoot, 'app.log'), 'log');
      await writeFile(join(repoRoot, 'node_modules', 'pkg', 'index.js'), 'module');
      await writeFile(join(repoRoot, 'README.md'), '# Readme');

      const filter = createFileFilter({ repoRoot });
      filter.setIgnoreMatcher(matcher);

      const results = await filter.filterFiles([
        'src/app.ts',
        'app.log',
        'node_modules/pkg/index.js',
        'README.md',
      ]);

      expect(results).toEqual(['src/app.ts', 'README.md']);
    });

    it('respects maxFileSize option', async () => {
      const matcher = createIgnoreMatcher([]);

      await writeFile(join(repoRoot, 'small.txt'), 'small');
      await writeFile(join(repoRoot, 'large.txt'), 'x'.repeat(1000));

      const filter = createFileFilter({ repoRoot, maxFileSize: 100 });
      filter.setIgnoreMatcher(matcher);

      const results = await filter.filterFiles(['small.txt', 'large.txt']);

      expect(results).toEqual(['small.txt']);
    });

    it('respects detectBinary option', async () => {
      const matcher = createIgnoreMatcher([]);

      await writeFile(join(repoRoot, 'image.png'), Buffer.from([0x89, 0x50, 0x4e, 0x47]));

      const filter = createFileFilter({ repoRoot, detectBinary: false });
      filter.setIgnoreMatcher(matcher);

      const results = await filter.filterFiles(['image.png']);

      // With detectBinary: false, binary files are not filtered out
      expect(results).toEqual(['image.png']);
    });

    it('respects detectGenerated option', async () => {
      const matcher = createIgnoreMatcher([]);

      await writeFile(join(repoRoot, 'generated.ts'), '// @generated\nexport const x = 1;');

      const filter = createFileFilter({ repoRoot, detectGenerated: false });
      filter.setIgnoreMatcher(matcher);

      const results = await filter.filterFiles(['generated.ts']);

      expect(results).toEqual(['generated.ts']);
    });
  });

  describe('createFileFilter', () => {
    it('creates FileFilter instance', () => {
      const filter = createFileFilter({ maxFileSize: 5000000 });

      expect(filter).toBeInstanceOf(Object);
    });
  });
});
